POST http://localhost:8081/api/v1/inventories HTTP/1.1
content-type: application/json

{
    "itemcode": "100003",
    "label": "Apple",
    "netprice": "1000",
    "price": "1000",
    "isinfinite": false,
    "counts": 10,
    "tag": "Fruit",
    "remark": "Testing inventory"
}

